### ISSUE TITLE
Italics with single * doesn't work now

### ISSUE THREAD

**Issue by aanchalgera** [withspectrum/draft-js-markdown-plugin#152]
Earlier, italics used to work when wrapped with single *. Now, `*abc*` makes it bold.

**Comment by mxstbr** [comment]
Yep, that change was made on purpose because it allowed us to trigger markdown on the completion of the symbols rather than space. E.g. `**some text** |` (note the space) was required before to make some text bold, but now it triggers at `*some text*|`  (note no space). We couldn't do that with single-asteriks-italic, as one would run into this edge case: `**some text*|`. What do you do now?

I hope that makes sense!

**Comment by aanchalgera** [comment]
But that defies the whole purpose of the plugin. We can't tell our users to stop using single * for italic because we stopped supporting it :-(

**Comment by mxstbr** [comment]
That's what we did—if you don't like that you can totally keep using the old version!
