### ISSUE TITLE
Applies on space even when the cursor is inside formatted text and not at the end

### ISSUE THREAD

**Issue by superbryntendo** [withspectrum/draft-js-markdown-plugin#8]
![image](https://user-images.githubusercontent.com/4926824/31972227-7046812e-b8d4-11e7-8a01-e7c094a77b15.png)

**Comment by mxstbr** [comment]
Unsure what to do here. We have two options:

1. Either we make it so pressing space applies the styling even from inside the block BUT the cursor doesn't get moved to the end
2. We make it so only pressing space directly after the last asteriks applies the styling

I'm leaning towards the first solution, because we have to consider the case where a users doesn't go after the asterisk and press space. Imagine the following:

This is the first state, | is the cursor position: 

> \*\*This should bold\*\*|

Currently, nothing is bold. If the users pressed "SPACE" now, it would turn bold. Instead, they move the cursor back inside the text to fix their grammar issue:

> \*\*This should |bold\*\*

Now they enter some new text:

> \*\*This should be|bold\*\*

But now, if we don't make it bold when they press space, we end up in this state:

> \*\*This should be |bold\*\*

This sucks, because if they don't manually move the cursor to after the `**` and press space this text will never be bold. :confused: What do you think about making it bold anyway, but just not moving the cursor? Then we'd end up in this state:

> **This should be |bold**

That seems like the best solution to me?

**Comment by brianlovin** [comment]
@mxstbr could we also have the following behaviors:
- on 'enter' press we calculate text formatting (so that if I type `*foo*` and immediately press enter, it will calculate the italics)
- on post publish we calculate text formatting (so that if the last line and last words of my post are formatted, and I have no reason to press space or enter, it will still be formatted properly when published)

?

**Comment by mxstbr** [comment]
> on 'enter' press we calculate text formatting 

That for sure, been wanted to implement that! The "on post publish" isn't possible as the plugin is architected right now I don't think. That'd require a whole revamp.

**Comment by brianlovin** [comment]
> That for sure, been wanted to implement that!

Small wins!

**Comment by mxstbr** [comment]
Enter-to-format was implemented in #11!
