### ISSUE TITLE
Pasting code is totally broken - each line creates a new code block element

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/draft-js-markdown-plugin#88]
Pasting 
```js
getRawMarkup() {
    const md = new Remarkable();
    return { __html: md.render(this.state.value) };
  }
```
looks like this:
![screenshot 2018-06-06 15 38 39](https://user-images.githubusercontent.com/1923260/41068731-c31c1d10-699f-11e8-8792-d1bca66f08c3.png)

@mxstbr can we please hotfix this? We have lots of developer communities moving over and this is really really painful.

**Comment by juliankrispel** [comment]
I'm looking at this. @mxstbr sent you a message - a little stuck with the env setup for spectrum (unfortunately I need to start the entire app to test and debug this) - maybe it'd be worth adding a story to contain this or something...

**Comment by mxstbr** [comment]
@juliankrispel you might be able to hack around it by doing

```
$ yarn
$ yarn run dev:web
```

and then opening `localhost:3000/new/thread`?

**Comment by juliankrispel** [comment]
@mxstbr ok - figured it out. Basically the results were always consistent, you get separate code blocks in the markdown plugin as well - it's just that the css in Spectrum puts a margin on code blocks :D 

Opened a pr with a change that inserts plain text when pasted into code blocks #90  rather than default handling...
